### ISSUE TITLE
Support for Cocoapods

### ISSUE THREAD

**Issue by superwave** [IABTechLab/uid2-ios-sdk#14]
Hi iAB team, I came across this from the [UID2 SDK for iOS](https://unifiedid.com/docs/sdks/uid2-sdk-ref-ios#getadvertisingtoken) document.
I am looking to reference UID2 as an external dependency in our SSP advertising SDK via Cocoapods.

However, currently, UID2 only supports the Swift Package Manager. I would like to inquire if there are any plans to support Cocoapods in the future? 

Or, would it be possible for us to proceed by forking the repository?

Thank you : )

Below is the suggested pod spec file, if it helps
```
Pod::Spec.new do |s|
  s.name         = "UID2"
  s.version      = "0.2.0" # Specify your library's current version
  s.summary      = "You can use the UID2 SDK for iOS to facilitate the process of establishing client identity using UID2 and retrieving advertising tokens on iOS devices" 
  s.homepage     = "https://iabtechlab.com/opensource" 
  s.license      = { :type => "[MIT]", :file => "[LICENSE]" } 
  s.author       = { "[Your Name]" => "[your@email.com]" }
  s.source       = { :git => "https://github.com/IABTechLab/uid2-ios-sdk.git", :tag => "#{s.version}" }
  s.platform     = :ios, "13.0"
  s.swift_version = '5.7' 
  s.source_files  = "UID2/**/*.{h,m,swift}" 
  s.resource_bundles = {
    'UID2' => ['UID2/Properties/*.plist'] 
  }

  s.test_spec 'Tests' do |test_spec|
    test_spec.source_files = 'UID2Tests/**/*.{h,m,swift}'
    test_spec.resources = "UID2Tests/TestData/*" 
  end
end
```

**Comment by sunnywu** [comment]
Hi @superwave really sorry for missing your issue here earlier. Have you resolved your Cocoapods issue (e.g. forking) or are you still looking for Cocoapods support from us? Thanks

**Comment by superwave** [comment]
Yes, we’ve resolved this issue by forking the UID2 SDK file directly into our project. 

We see that the UID2 SDK now supports CocoaPods in version 1.2.4.

 Thank you for your support! we will try this :tada:

**Comment by sunnywu** [comment]
Hi @superwave, i was about to reply just now and saw your reply  :)

as you mentioned we have added cocoapods support please see 
https://cocoapods.org/pods/UID2

and we have updated our iOS reference guides with the according instructions [here](https://unifiedid.com/docs/sdks/uid2-sdk-ref-ios#installing-with-cocoapods)

I wiill close this issue - if you have any new feedback please tag me in a new GitHub issue thanks!
